Repository puppetlabs/ace, pull requests merged in 2019-10, with the labels that each got.

#59 (FM-8497) File Mutex changes
  agentless-catalog-executor.gemspec
  lib/ace/file_mutex.rb
  lib/ace/plugin_cache.rb
  lib/ace/transport_app.rb
  spec/acceptance/ace/transport_app_spec.rb
  spec/unit/ace/file_mutex_spec.rb
  spec/unit/ace/plugin_cache_spec.rb
Labels: bug

#60 (FM-8566) Add additional error handling for /run_task
  lib/ace/transport_app.rb
  spec/unit/ace/transport_app_spec.rb
Labels: bug

#55 (FM-8503) implement transport loading if there is no device.rb shim
  lib/ace/transport_app.rb
  spec/acceptance/ace/transport_app_spec.rb
  spec/unit/ace/transport_app_spec.rb
Labels: enhancement

#63 (QENG-7501) Minor formatting change to push tag in build pipeline
  README.md
Labels: maintenance
