Repository puppetlabs/ace, pull requests merged in 2019-08, with the labels that each got.

#48 (PE-27024) return detailed results from `/execute_catalog`
  README.md
  developer-docs/docker.md
  lib/ace/transport_app.rb
  spec/acceptance/ace/transport_app_spec.rb
  spec/unit/ace/transport_app_spec.rb
Labels: bug, enhancement

#50 (FM-8446) remove remote-transport requirement
  lib/ace/schemas/ace-run_task.json
  spec/unit/ace/transport_app_spec.rb
Labels: enhancement

#51 (FM-8481) Add missing headers for native extensions
  Dockerfile
Labels: bug
